#!/usr/bin/env python3
"""
Memory Drain Daemon — surface unconsumed decision breadcrumbs.

Reads logs/decisions_pending_memory.jsonl (written by breadcrumb_actions.py),
tracks a watermark of last-processed-ts so we don't re-alert on the same decisions,
and emits any new decisions to stderr (for cron log) and optionally to a
dated markdown report at reports/memory_drain_YYYY-MM-DD.md.

DOES NOT auto-merge into MEMORY.md. Team lead owns that decision.

Usage:
    python3 scripts/memory_drain_daemon.py                 # emit unread to stderr
    python3 scripts/memory_drain_daemon.py --auto-append   # also append to dated report
    python3 scripts/memory_drain_daemon.py --reset         # wipe watermark (re-emit all)
    python3 scripts/memory_drain_daemon.py --quiet         # exit silently if nothing new

Stdlib only. Idempotent on repeated runs via watermark file.
"""
import argparse
import datetime as dt
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
QUEUE = REPO / "logs" / "decisions_pending_memory.jsonl"
WATERMARK = REPO / "logs" / "memory_drain_watermark.txt"
REPORTS = REPO / "reports"


def read_watermark() -> str:
    if WATERMARK.exists():
        return WATERMARK.read_text(errors="replace").strip()
    return ""


def write_watermark(ts: str) -> None:
    WATERMARK.parent.mkdir(parents=True, exist_ok=True)
    WATERMARK.write_text(ts + "\n")


def load_unread(watermark: str):
    if not QUEUE.exists():
        return []
    seen = set()  # (ts, content) dedup — queue has dup writes
    out = []
    for line in QUEUE.read_text(errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except json.JSONDecodeError:
            continue
        ts = entry.get("ts", "")
        content = entry.get("content", "")
        if not ts or not content:
            continue
        if ts <= watermark:
            continue
        key = (ts, content)
        if key in seen:
            continue
        seen.add(key)
        out.append(entry)
    out.sort(key=lambda e: e.get("ts", ""))
    return out


def emit(entries, auto_append: bool) -> pathlib.Path | None:
    for e in entries:
        ts = e.get("ts", "?")
        src = e.get("source", "cc")
        content = e.get("content", "")
        sys.stderr.write(f"[MEMORY DRAIN] [{ts}] ({src}) {content}\n")

    if not auto_append or not entries:
        return None

    today = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    report = REPORTS / f"memory_drain_{today}.md"
    REPORTS.mkdir(parents=True, exist_ok=True)
    new_file = not report.exists()
    with report.open("a") as f:
        if new_file:
            f.write(f"# Memory Drain Report — {today}\n\n")
            f.write(
                "Auto-generated by `scripts/memory_drain_daemon.py`. "
                "Team lead reviews and decides which entries fold into MEMORY.md. "
                "DO NOT auto-merge.\n\n"
            )
        stamp = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
        f.write(f"## Drain run @ {stamp}\n\n")
        f.write(f"{len(entries)} new decision(s) since last watermark.\n\n")
        for e in entries:
            ts = e.get("ts", "?")
            src = e.get("source", "cc")
            content = e.get("content", "")
            f.write(f"- **[{ts}]** ({src}) {content}\n")
        f.write("\n")
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    parser.add_argument("--auto-append", action="store_true",
                        help="Also append unread entries to reports/memory_drain_YYYY-MM-DD.md")
    parser.add_argument("--reset", action="store_true",
                        help="Wipe the watermark so every entry is re-emitted")
    parser.add_argument("--quiet", action="store_true",
                        help="Exit silently (non-zero status code) if nothing new")
    args = parser.parse_args()

    if args.reset and WATERMARK.exists():
        WATERMARK.unlink()

    watermark = read_watermark()
    entries = load_unread(watermark)

    if not entries:
        if not args.quiet:
            sys.stderr.write(
                f"[MEMORY DRAIN] nothing new since watermark={watermark or '(none)'}\n"
            )
        return 0

    report = emit(entries, auto_append=args.auto_append)

    latest = max(e.get("ts", "") for e in entries)
    write_watermark(latest)

    summary = f"[MEMORY DRAIN] emitted {len(entries)} new decision(s), watermark advanced to {latest}"
    if report is not None:
        summary += f", appended to {report.relative_to(REPO)}"
    sys.stderr.write(summary + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
